# Generated by Django 4.2.16 on 2024-10-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Weather', models.CharField(max_length=250)),
                ('Location', models.CharField(max_length=2000)),
                ('Map_link', models.URLField(blank=True)),
                ('Tour_img', models.ImageField(upload_to='tour/')),
                ('Description', models.CharField(max_length=5000)),
            ],
        ),
    ]
